version: '3.8'

services:
  neso-watch:
    build:
      context: .
      dockerfile: Dockerfile.hassio
    container_name: neso-watch
    environment:
      - DEBUG=${DEBUG:-false}
      - CHECK_INTERVAL=${CHECK_INTERVAL:-300}
    volumes:
      - ./data:/data
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 