# Sensors for Neso Octowatch integration
- platform: file
  name: Octopus Neso Status
  file_path: /data/neso_octowatch/states.json
  value_template: "{{ value_json.octopus_neso_status.state }}"
  json_attributes:
    - attributes

- platform: file
  name: Octopus Neso Utilization
  file_path: /data/neso_octowatch/states.json
  value_template: "{{ value_json.octopus_neso_utilization.state }}"
  json_attributes:
    - attributes

- platform: file
  name: Octopus Neso Highest Accepted
  file_path: /data/neso_octowatch/states.json
  value_template: "{{ value_json.octopus_neso_highest_accepted.state }}"
  json_attributes:
    - attributes