name: "NESO Octopus Watch"
version: "1.0.0"
slug: "neso_octopus_watch"
description: "Monitor Octopus Energy's participation in the NESO DFS market"
url: "https://github.com/yourusername/neso_octowatch"
arch:
  - amd64
  - aarch64
  - armv7
  - armhf
  - i386
init: false
startup: application
boot: auto
map:
  - share:rw
options:
  check_interval: 300
schema:
  check_interval: int
homeassistant_api: true 